import Phaser from 'phaser';

export const EventBus = new Phaser.Events.EventEmitter();

export const Events = {
  GAME_READY: 'game:ready',
  GAMEPLAY_STARTED: 'gameplay:started',
  GAMEPLAY_STOPPED: 'gameplay:stopped',
  SAVE_REQUESTED: 'save:requested',
  SAVE_LOADED: 'save:loaded',
  MONEY_CHANGED: 'money:changed',
  STATS_CHANGED: 'stats:changed',
  PRODUCT_CHANGED: 'product:changed',
  SHELF_STOCKED: 'shelf:stocked',
  ALL_STOCK_EMPTY: 'stock:all-empty',
  CUSTOMER_LEFT: 'customer:left',
  PLAYER_TELEPORTED: 'player:teleported',
  CHECKOUT_REQUESTED: 'checkout:requested',
  CHECKOUT_COMPLETED: 'checkout:completed',
  UPGRADE_PURCHASED: 'upgrade:purchased',
  ZONE_UNLOCKED: 'zone:unlocked',
  ROUTES_CHANGED: 'routes:changed',
  DAY_ROLLED: 'day:rolled',
  DAILY_REWARD_CLAIMED: 'daily:reward:claimed',
  OFFLINE_PROGRESS: 'offline:progress',
  PRESTIGE_READY: 'prestige:ready',
  PRESTIGE_CLAIMED: 'prestige:claimed',
  AD_REWARDED: 'ad:rewarded',
  AD_FULLSCREEN_CLOSED: 'ad:fullscreen:closed',
  UI_TOAST: 'ui:toast',
  UI_BUY_UPGRADE: 'ui:buy:upgrade',
  UI_UNLOCK_ZONE: 'ui:unlock:zone',
  UI_RESTOCK_SHELF: 'ui:restock:shelf',
  UI_SHELF_SELECTED: 'ui:shelf:selected',
  UI_PANEL_TOGGLED: 'ui:panel:toggled',
  UI_BUY_CUSTOMER_SPEED: 'ui:buy:customer-speed',
  UI_BUY_CUSTOMER_FLOW: 'ui:buy:customer-flow',
  UI_CLAIM_DAILY: 'ui:claim:daily',
  UI_CLAIM_PRESTIGE: 'ui:claim:prestige',
  UI_SHOW_REWARDED: 'ui:show:rewarded',
};
